### ISSUE TITLE
Consider replacing mongoose-csv?

### ISSUE THREAD

**Issue by gaborszita** [Eaglestrike/Eaglescout-2022#5]
I was skimming through some code in the past few days, not really doing much though, just looking through it cause why not. I noticed that in this project there's a critical vulnerability caused by mongoose-csv, because it depends on vulnerable version lodash. There is a pull request to fix this on mongoose-csv, but it's been open now for like 4 years and I doubt it will ever be fixed. So, I think it is time to replace this dependency with something else. There are many alternatives, like [mongoose-csv-export](https://www.npmjs.com/package/mongoose-csv-export). I can fix this actually, just wanted to check if you agree with it.

**Comment by Versus7** [comment]
Go for it. Make a new branch, then you can swap it in `observation.js` (or wherever else you see it), and we'll deploy + test your changes on Monday since it's not super urgent and to make sure we don't lose any data.
